config/routes.rb
Rails.application.routes.draw do
  get 'projects', to: 'projects#index', as: :projects
  get 'projects/:id', to: "projects#show", as: :project
  get 'about', to: 'pages#about', as: :about
  get 'contact', to: 'pages#contact', as: :contact
  resources :contacts, only: [:new, :create]
  root to: 'pages#home'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/contact.rb
class Contact < ApplicationRecord
  validates :full_name, presence: true
  validates :email, presence: true, format: { with: /\A([\w+\-].?)+@[a-z\d\-]+(\.[a-z]+)*\.[a-z]+\z/i }
  validates :subject, presence: true
  validates :message, presence: true
end

app/models/project.rb
class Project < ApplicationRecord
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
    def new
      @contact = Contact.new
    end
  
    def create
      @contact = Contact.new(contact_params)
      if @contact.save
        ContactMailer.contact_email(@contact).deliver_now
        redirect_to projects_path
      else
        render :new
      end
    end

    private
    def contact_params
      params.require(:contact).permit(:full_name, :email, :subject, :message)
    end
  
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
    # respond_to do |format|
    #   format.html {root_path}
    #   format.js #app/views/pages/home.js.erb
    # end
  end

  def contact
  end

  def about
  end

  private
  def contact_params
    params.require(:contact).permit(:full_name, :email, :message)
  end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  def index
    @contacts = Contact.all
    @skills = %w(All Ruby\ on\ Rails Javascript Action\ Cable)
    if params[:query].present?
      sql_query = "title ILIKE :query OR skill ILIKE :query"
      @projects = Project.where(sql_query, query: "%#{params[:query]}%").order("LOWER(title)")
    elsif params[:skill]
      @projects = Project.where("skill ILIKE :query", query: "%#{params[:skill]}%").order("LOWER(title)")
    else
      @projects = Project.all.order("LOWER(title)")
    end
    respond_to do |format|
      format.html
      format.js
    end
  end

  def show
    @project = Project.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/contacts/new.html.erb
<div class="container" id="contact-container">
  <h1 class="text-center mb-0">Want to work together or have inquiries?</h1>
  <div class="social_icons my-4 py-4 text-center">
    <%= link_to 'https://www.facebook.com/taiseiyamadashindosu', class: "icons", target: :blank do %>
        <i class="fab fa-facebook-f fa-sm arrow" id="facebook"></i>   
    <% end %>
    <%= link_to 'https://www.instagram.com/taiseiyamadas/', class: "icons", target: :blank do %>
        <i class="fab fa-instagram fa-sm arrow"></i>   
    <% end %>
    <%= link_to 'https://twitter.com/TaiseiYamada4', class: "icons", target: :blank do %>
        <i class="fab fa-twitter fa-sm arrow"></i>
    <% end %>
    <%= link_to 'https://line.me/R/ti/p/tyamada2014', class: "icons", target: :blank do %>
        <i class="fab fa-line fa-sm arrow"></i>
    <% end %>
    <%= link_to 'https://www.linkedin.com/in/taisei-yamada/', class: "icons", target: :blank do %>
        <i class="fab fa-linkedin fa-sm arrow"></i>
    <% end %>
    <%= link_to 'https://github.com/shindosu', class: "icons", target: :blank do %>
        <i class="fab fa-github fa-sm arrow"></i>
    <% end %>
  </div>
  <%= simple_form_for @contact, html:{class: "mt-3"} do |f| %>
  <%= f.input :full_name, placeholder: 'FULL NAME', label: false %>
  <%= f.input :email, placeholder: 'EMAIL', label: false %>
  <%= f.input :subject, placeholder: 'SUBJECT', label: false %>
  <%= f.input :message, placeholder: 'MESSAGE', label: false %>
  <div class="buttonholder text-center mt-4">
    <%= f.submit "SEND", class: "btn btn-danger px-4 rounded-0 submit-button", 'data-toggle': "modal", 'data-target': "#exampleModalCenter" %>
  </div>
  
<% end %>

<%= render 'shared/email_confirmation' %>
</div>

 

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="Personal portfolio of Taisei Yamada, a Japanese Full Stack Web Developer" />
    <meta name="author" content="Taisei Yamada">
    <meta name="owner" content="Taisei Yamada">
    <meta name="copyright"content="Copyright ©2019 Taisei Yamada">
    <meta content="TAISEI YAMADA" property="og:title">
    <meta content="Personal portfolio of Taisei Yamada, a Japanese Full Stack Web Developer" property="og:description">
    <meta content="Taisei Yamada, Japan, Tokyo, Nagoya, HTML, CSS, Javascript, Ruby on Rails, Developer, Development, Design, React, Le Wagon " name="keywords">
    <meta content="http://www.taiseiyamada.com" property="og:url">
    <meta content="website" property="og:type">
    <title>Taisei Yamada</title>
    <%= favicon_link_tag asset_path('android-icon-36x36.png') %>
    <%= csrf_meta_tags %>
    <%= action_cable_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all' %>
    <%#= stylesheet_pack_tag 'application', media: 'all' %> <!-- Uncomment if you import CSS in app/javascript/packs/application.js -->
  </head>
  <body>
    <%= render "shared/about_link" %>
    <%= render "shared/navbar" %>
    <%= yield %>
    <%= render 'shared/root_path_links' %>
    <%= render 'shared/projects_path_links' %>
    <%= render 'shared/contact_path_links' %>
    <%= javascript_include_tag 'application' %>
    <%= javascript_pack_tag 'application' %>
  </body>
</html>

app/views/pages/about.html.erb
<div class="container text-center" id="about-container">
  <p>Coming soon...👺</p>
</div>

app/views/pages/contact.html.erb
<div class="container text-center">
  <h1>Want to work together or have inquiries?</h1>
  <div class="social_icons">
    <%= link_to 'https://www.facebook.com/taiseiyamadashindosu', class: "mr-3" do %>
      <span class="fa-stack fa-2x">
        <i class="fas fa-circle fa-stack-2x"></i>
        <i class="fab fa-facebook-f fa-stack-1x fa-inverse"></i> 
      </span>   
    <% end %>
    <%= link_to 'https://www.instagram.com/taiseiyamadas/', class: "mr-3" do %>
      <span class="fa-stack fa-2x">
        <i class="fas fa-circle fa-stack-2x"></i>
        <i class="fab fa-instagram fa-stack-1x fa-inverse"></i>  
      </span>  
    <% end %>
    <%= link_to 'https://twitter.com/TaiseiYamada4', class: "mr-3" do %>
      <span class="fa-stack fa-2x">
        <i class="fas fa-circle fa-stack-2x"></i>
        <i class="fab fa-twitter fa-stack-1x fa-inverse"></i>
      </span> 
    <% end %>
    <%= link_to 'https://line.me/R/ti/p/tyamada2014', class: "mr-3" do %>
      <span class="fa-stack fa-2x">
        <i class="fas fa-circle fa-stack-2x"></i>
        <i class="fab fa-line fa-stack-1x fa-inverse"></i>
      </span> 
    <% end %>
    <%= link_to 'https://www.linkedin.com/in/taisei-yamada/', class: "mr-3" do %>
      <span class="fa-stack fa-2x">
        <i class="fas fa-circle fa-stack-2x"></i>
        <i class="fab fa-linkedin fa-stack-1x fa-inverse"></i>
      </span> 
    <% end %>
    <%= link_to 'https://github.com/shindosu', class: "mr-3" do %>
      <span class="fa-stack fa-2x">
        <i class="fas fa-circle fa-stack-2x"></i>
        <i class="fab fa-github fa-stack-1x fa-inverse"></i>
      </span> 
    <% end %>
  </div>
</div>

app/views/pages/home.html.erb
<div class="container d-flex justify-content-center align-items-center" id="circle-container">
  <div class="circle"></div>
</div>

app/views/pages/home.js.erb
alert("helo");

app/views/projects/index.html.erb
<div class="container" id="project-container">
<div class="skill-set">
  <% @skills.each_with_index do |skill, index| %>
    <% if skill == "All" %>
      <%= link_to skill, projects_path, class: "btn btn-danger h-100 rounded-0", remote: true%>
    <% else %>
      <%= link_to skill, projects_path(skill: skill), class: "btn h-100 rounded-0", remote: true %>
    <% end %>
  <% end %>
</div>

  <div class="d-flex mt-5 card-holder">
    <% @projects.each do |project| %>
      <%= render 'shared/card', project: project %>
      <%= render 'shared/show_modal', project: project %>
    <% end %>
  </div>
</div>

<div class="w-50 d-none">
  <%= simple_form_for projects_path, method: :get, html:{class: "search-form d-flex ml-3 mt-3"} do %>
  <%= text_field_tag :query,
  params[:query],
  class: "form-control mr-2",
    placeholder: "Ruby, Responsive, etc.."
    %>
    <%= button_tag(type: "submit", class: "btn btn-default") do %>
      <i class="fas fa-search"></i>
    <% end %>
  <% end %>
  </div>

app/views/projects/index.js.erb
if (window.location.href.includes("/projects")){

//Hide cards in which the skills don't match 
cardHolder = document.querySelectorAll(".card")
cardHolder.forEach(function(card){
  if (!card.querySelector('.d-none').innerText.includes("<%= params[:skill] %>")){
    card.classList.add("d-none")
  }
  else{
    card.classList.remove("d-none");
  }
})


//add red btn
button = document.querySelectorAll('.btn');
button_array = [button[0], button[1], button[2], button[3]];
skill = "<%= params[:skill] %>".toLowerCase()
function handleClick(){
  button_array.forEach(element => {
    element.classList.remove('btn-danger');
  });
  button_array.forEach(element => {
    if (element.innerText.toLowerCase() == (skill || "all")){
      element.classList.add('btn-danger');
    }
  });
};

handleClick();  
}

app/views/shared/_about_link.html.erb
<div class="about-side">
  <%= link_to about_path do %>
    <p class="pr-4 about-side" id="about">About <i class="far fa-user fa-sm arrow ml-2"></i></p>
  <% end %>
</div>

app/views/shared/_card.html.erb
<%= link_to "##{project.title.downcase.gsub(" ", "_")}", data: {toggle: "modal"}, class: "card-link" do %>
  <div class="card border-0 rounded-0">
    <%= image_tag(project.thumbnail, class: "card-image img-fluid")%> 
    <p class="d-none"><%= project.skill %></p>
      <div class="card-description d-none">
        <h3 class="card-title"><%= project.title %></h3>
        <p class="card-catch-phrase"><%= project.catch_phrase %></p>
      </div>
    <div class="card-buttonholder text-center d-none">
      <%= link_to 'LEARN MORE', "##{project.title.downcase.gsub(" ", "_")}", data: {toggle: "modal"}, class: "btn button-link rounded-0" %>
    </div>
  </div>
<% end %>

app/views/shared/_carousel.html.erb
<div id="carousel<%= project.title.downcase.gsub(" ","_") %>" class="carousel slide" data-ride="carousel" data-interval="false">
  <ol class="carousel-indicators mb-1">
    <% project.user_journey_image.gsub('"', '').gsub(/(\[|\]|\s)/,"").split(",").each_with_index do |image, index| %>
      <% if index == 0 %>
        <li data-target="#carousel<%= project.title.downcase.gsub(" ","_") %>" data-slide-to="<%=index%>" class="active mx-2"></li>
      <% else %>
        <li data-target="#carousel<%= project.title.downcase.gsub(" ","_") %>" data-slide-to="<%=index%>" class="mx-2"></li>
      <% end %>    
    <% end %>
  </ol>
  <div class="carousel-inner">
    <% project.user_journey_image.gsub('"', '').gsub(/(\[|\]|\s)/,"").split(",").each_with_index do |image, index| %>
      <% if index == 0 %>
        <div class="carousel-item active">
          <%= image_tag(project.user_journey_image.gsub('"', '').gsub(/(\[|\]|\s)/,"").split(",").first, class: "d-block w-100", size: "800x450")%>
        </div>
      <% else %>
        <div class="carousel-item">
          <%= image_tag(image, class: "d-block w-100", size: "800x450")%>
        </div>
      <% end %>
    <% end %>
  </div>
  <a class="carousel-control-prev" href="#carousel<%= project.title.downcase.gsub(" ","_") %>" role="button" data-slide="prev">
    <span class="carousel-control-prev-icon carousel-buttons" aria-hidden="true"></span>
    <span class="sr-only">Previous</span>
  </a>
  <a class="carousel-control-next" href="#carousel<%= project.title.downcase.gsub(" ","_") %>" role="button" data-slide="next">
    <span class="carousel-control-next-icon carousel-buttons" aria-hidden="true"></span>
    <span class="sr-only">Next</span>
  </a>
</div>

app/views/shared/_contact_path_links.html.erb
<% if current_page?(new_contact_path)%>
  <div class="left-side" id="contact-left">
    <%= link_to projects_path do %>
      <p class="m-4"><i class="fas fa-arrow-left fa-sm arrow mr-2"></i> Projects</p>
    <% end %> 
  </div>
  <div class="right-side" id="contact-right">
    <%= link_to root_path do %>
      <p class="m-4">Home <i class="fas fa-arrow-right fa-sm arrow ml-2"></i></p>
    <% end %> 
  </div>
<% end %>

app/views/shared/_email_confirmation.html.erb
<div class="modal fade" id="exampleModalCenter" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
  <div class="modal-dialog modal-dialog-centered" role="document">
    <div class="modal-content">
      <div class="modal-header pb-0 border-0">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
      <h3>Email Sent <i class="far fa-thumbs-up"></i></h3>
        <p>Thanks <%= @contact.full_name %>! I'll get back to you!</p>
      </div>
    </div>
  </div>
</div>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-expand-md navbar-light p-0">
  <button class="hamburger hamburger--squeeze navbar-toggler mt-3" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
    <span class="hamburger-box">
      <span class="hamburger-inner"></span>
    </span>
  </button> 

  <div class="collapse navbar-collapse" id="navbarNav">
    <ul class="navbar-list p-0">
      <li class="nav-item">
        <%= link_to root_path do %>
          <%= image_tag 'logo', class: "logo" %>
        <% end %>
      </li>
      <li class="nav-item not-logo-link responsive-link">
        <% if current_page?(root_path)%>
          <%= link_to 'Home', root_path, class: "active-link"%>
        <% else %>
          <%= link_to 'Home', root_path, class: "nav-link"%>
        <% end %>
      </li>
      <li class="nav-item not-logo-link responsive-link">
        <% if current_page?(about_path)%>
          <%= link_to 'About', about_path, class: "active-link"%>
        <% else %>
          <%= link_to 'About', about_path, class: "nav-link" %>
        <% end %>
      </li>
      <li class="nav-item not-logo-link">
        <% if current_page?(projects_path)%>
          <%= link_to 'Projects', projects_path, class: "active-link"%>
        <% else %>
          <%= link_to 'Projects', projects_path, class: "nav-link"%>
        <% end %>
      </li>
      <li class="nav-item not-logo-link">
        <% if current_page?(new_contact_path)%>
          <%= link_to 'Contacts', new_contact_path, class: "active-link"%>
        <% else %>
          <%= link_to 'Contacts', new_contact_path, class: "nav-link"%>
        <% end %>
      </li>
    </ul>
  </div>
</nav>

app/views/shared/_projects_path_links.html.erb
<% if current_page?(projects_path)%>
  <div class="left-side">
    <%= link_to root_path do %>
      <p class="m-4"><i class="fas fa-arrow-left fa-sm arrow mr-2"></i> Home </p>
    <% end %> 
  </div>
  <div class="right-side">
    <%= link_to new_contact_path do %>
      <p class="m-4">Contact <i class="fas fa-arrow-right fa-sm arrow ml-2"></i></p>
    <% end %> 
  </div>
  <% end %>

app/views/shared/_root_path_links.html.erb
<% if current_page?(root_path) %>
  <div class="left-side" id="intro-description">
    <h1>Taisei</h1>
    <p>Full Stack Developer</p>
  </div>
  <div class="right-side" id="project-link-repsonsive">
    <%= link_to projects_path do %>
      <p class="m-4">Projects <i class="fas fa-arrow-right fa-sm arrow ml-2"></i></p>
    <% end %>  
  </div>
<% end %>

app/views/shared/_show_modal.html.erb
<div class="modal fade bd-example-modal-lg" id= "<%=project.title.downcase.gsub(" ", "_")%>"tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
  <div class="modal-dialog modal-dialog-centered modal-lg" role="document">
    <div class="modal-content">
      <div class="modal-body p-0">
        <%= render 'shared/carousel', project: project%>
        <div class="skill-used">
          <ul class="list-group list-group-horizontal">
            <% project.skill.gsub('"', '').gsub(/(\[|\]|)/,"").split(",").each do |skill| %>
              <li class="list-group-item mr-3 mt-2 border border-danger py-1 px-2 d-flex align-items-center"><p class="m-0"><%= skill %></p></li>
            <% end %>
            <% if project.responsiveness %>
              <li class="mr-3 mt-2 py-1 px-2 d-flex align-items-center responsive responsive-or-not"><p class="m-0">RESPONSIVE</p></li>
            <% else %>
              <li class="mr-3 mt-2 py-1 px-2 d-flex align-items-center not-responsive responsive-or-not"><p class="m-0">NOT RESPONSIVE</p></li>
            <% end %>
          </ul>
        </div>
        <div class="info mx-4 mt-4 border-bottom">
          <h3 class="show-title mb-1"><%= project.title %></h3>
          <p class="catch-phrase mb-0"><%= project.catch_phrase %></p>
        </div>
        <p class="mx-4 mt-4"><%= project.description %></p>
        <div class="modal-footer d-flex justify-content-between border-0 px-0 mx-3">
          <div class="buttons">
            <%= link_to "https://#{project.demo_link}", class: "btn btn-danger rounded-0", target: :blank do%>
              <p class="mb-0"><i class="far fa-eye"></i> Demo</p>
            <% end %>
            <%= link_to "http://www.#{project.code_link}", class: "btn btn-danger rounded-0 ml-4", target: :blank do%>
              <p class="mb-0 rounded-0"><i class="fas fa-code"></i> Code</p>
            <% end %>
          </div>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
        </div>
      </div>
    </div>
  </div>
</div>